# Generated by Django 4.2.1 on 2023-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_number_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
