# Generated by Django 4.2.1 on 2023-05-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('bonus', 'Bônus'), ('poupanca', 'Poupança')], default='normal', max_length=10),
        ),
    ]
