name: Build Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tag:
    runs-on: ubuntu-latest
    container:
      image: bitnami/git:2-debian-11
    env:
      TOKEN_CI: ${{ secrets.TOKEN_CI }}
    steps:
      - name: Tag Git
        shell: bash
        run: | 
          git clone "https://${TOKEN_CI}@github.com/paulovanzo/gcm-api.git" && cd gcm-api
          LAST_TAG=$(git tag -l --sort=-v:refname | grep build | head -n 1 )
          LAST_VERSION=$(echo $LAST_TAG | sed 's/build-//')
          if [ -z $LAST_VERSION ]; then LAST_VERSION="0.0"; fi
          IFS=. read MAJOR MINOR <<< $LAST_VERSION
          NEXT_MINOR=$((MINOR + 1))
          NEXT_VERSION="$MAJOR.$NEXT_MINOR"
          TAG_NAME="build-$NEXT_VERSION"
          git tag $TAG_NAME
          git push --tags
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install hadolint
        run: |
          curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Check Dockerfile with hadolint
        run: hadolint Dockerfile --config hadolint.yaml

      - name: Build the Docker image
        run: docker build --build-arg DJANGO_SECRET_KEY=$SECRET_KEY . -t gcm-api:$(date +%s) 
