name: Build Workflow

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install hadolint
        run: |
          curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Check Dockerfile with hadolint
        run: hadolint Dockerfile --config hadolint.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: zedsousa
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          target: app
          tags: zedsousa/gcm-api:${{ steps.extract_branch.outputs.branch }}
          build-args: DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}