name: Docker Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.$TOKEN_CI }}
          fetch-depth: 0

      - name: Generate Build
        run: |
          LAST_TAG=$(git tag -l --sort=-v:refname | grep build | head -n 1 )
          LAST_VERSION=$(echo $LAST_TAG | sed 's/build-//')
          if [ -z $LAST_VERSION ]; then LAST_VERSION="0.0"; fi
          ARR=$(echo $LAST_VERSION | sed s/build-//g | tr -s '.' ' ' | xargs -n 1)
          MAJOR=${ARR[0]}
          MINOR=${ARR[1]}
          NEXT_MINOR=$((MINOR + 1))
          NEXT_VERSION="$MAJOR.$NEXT_MINOR"
          TAG_NAME="build-$NEXT_VERSION"
          git tag $TAG_NAME
          git push --tags

      - name: Install hadolint
        run: |
          curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Check Dockerfile with hadolint
        run: hadolint Dockerfile --config hadolint.yaml

      - name: Build the Docker image
        run: docker build --build-arg DJANGO_SECRET_KEY=$SECRET_KEY . -t gcm-api:$(date +%s) 
