name: Docker Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Build
        run: |
          TAG_NAME="build-$(date "+%s")"
          git tag $TAG_NAME
          git push --tags

      - name: Install hadolint
        run: |
          curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Check Dockerfile with hadolint
        run: hadolint Dockerfile --config hadolint.yaml

      - name: Build the Docker image
        run: docker build --build-arg DJANGO_SECRET_KEY=$SECRET_KEY . -t gcm-api:$(date +%s) 
