name: Testes Unitários Workflow

on:
  push:
    tags:
      - 'rel-*'
      - 'rc-*'
    branches:
      - develop
      - release

  pull_request:
    branches:
      - develop
      - release

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install project dependencies
      run: poetry install --no-root

    - name: Run tests
      run: poetry run python manage.py test
